In [1]:
import numpy as np
import numpy.random as rand
import decimal

In [2]:
#constant function
def const_function(v):
  return 1

In [10]:
#the sum of elements
def sum_function(v):
    sum = 0
    for i in range(0, len(v)):
        sum += v[i]
    return sum

In [16]:
#the product of elements
def prod_function(v):
    prod = 1
    for i in range(0, len(v)):
        prod *= v[i]
    return prod

In [22]:
#direct calculation P(x)
def poly_direct_function(v, x):
    decimal.getcontext().prec = 100 #to avoid overflow
    res = 0
    for i in range(len(v)):
        res += decimal.Decimal(v[i]) * (decimal.Decimal(x) ** decimal.Decimal(i))
    return res

In [38]:
#Horner's calculation P(x)
def poly_horner_function(v, x):
    res = v[len(v)-1]
    for i in range(len(v)-2, -1, -1):
        res = res * x + v[i]
    return res

In [43]:
#Bubble sort
def bubble_sort_function(v):
    for i in range(len(v)):
        for j in range(0, len(v)-i-1):
            if v[j] > v[j+1]:
                v[j], v[j+1] = v[j+1], v[j]
    return v

In [46]:
#Quick sort
def quick_sort_function(v):
    return np.sort(v, kind='quicksort')

In [52]:
#Timsort релизовать самостоятельно
def timsort_function(v):
    return np.sort(v, kind='stable')

In [56]:
#matrix product реализовать самостоятельно

def matrix_prod_function(A, B):
    return np.matmul(A, B)

#matrix generation

n = 3
A_matrix = np.random.randint(100, size=(n, n))
B_matrix = np.random.randint(100, size=(n, n))
print('A: ', A_matrix)
print('B: ', B_matrix)

matrix_prod_function(A_matrix, B_matrix)


    

A:  [[35 66 16]
 [28 77 77]
 [80 74 68]]
B:  [[54 78 45]
 [94 62 74]
 [37 32 41]]


array([[ 8686,  7334,  7115],
       [11599,  9422, 10115],
       [13792, 13004, 11864]])

In [53]:
#Vector generation
vector = np.random.uniform(low=0, high=100, size=7)
print("initial: ", vector)
print(sum_function(vector))
v2 = [5, 6, 9, 8]
v3 = [7, 1, 0]
print(poly_direct_function(v2, x=1.5))
print(poly_horner_function(v2, x=1.5))
print(poly_horner_function(v3, x=1.5))
print(bubble_sort_function(vector))
print(bubble_sort_function(v2))
print(bubble_sort_function(v3))
print(quick_sort_function(vector))
print(timsort_function(vector))
# for n in range(1, 2001):
#     for i(5):
#         vector = np.

initial:  [30.72524968 72.88250984 39.00784075 87.3531659  27.73540937 99.46487503
 67.59347721]
424.76252777709544
61.250
61.25
8.5
[27.73540937 30.72524968 39.00784075 67.59347721 72.88250984 87.3531659
 99.46487503]
[5, 6, 8, 9]
[0, 1, 7]
[27.73540937 30.72524968 39.00784075 67.59347721 72.88250984 87.3531659
 99.46487503]
[27.73540937 30.72524968 39.00784075 67.59347721 72.88250984 87.3531659
 99.46487503]
